### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by gauravv7** [paytm/Paytm_Python_Checksum#8]
env details:
Py Interpreter: Python 3.9.6
OS: 
- Darwin LM0002232 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64 Big-Sur
&
- Windows 10 

**Problem:** 

`
Traceback (most recent call last):
  File "/pyprojects/py_env3.9/paytm_enquiry/enquire_paytm.py", line 6, in <module>
    from paytmchecksum import PaytmChecksum
  File "/pyprojects/py_env3.9/lib/python3.9/site-packages/paytmchecksum/__init__.py", line 1, in <module>
    from .PaytmChecksum import generateSignature, verifySignature, encrypt, decrypt
  File "/pyprojects/py_env3.9/lib/python3.9/site-packages/paytmchecksum/PaytmChecksum.py", line 7, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
`

pip freeze:
`
certifi==2021.10.8
charset-normalizer==2.0.7
crypto==1.4.1
idna==3.2
Naked==0.1.31
path==16.2.0
paytmchecksum==1.7.0
pycryptodome==3.11.0
PyYAML==5.4.1
requests==2.26.0
shellescape==3.8.1
`

even if we install pycrypto, it still gives below error:

`
  File "/projects/backend/pyprojects/py_env3.9/lib/python3.9/site-packages/crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
ModuleNotFoundError: No module named 'Crypto'

`

**Solution:**
- either create a softlink for Cryptodome -> Crypto
- or we can submit a merge request to change line in `https://github.com/paytm/Paytm_Python_Checksum/blob/master/paytmchecksum/PaytmChecksum.py#L7`

**change:** 
`from Crypto.Cipher import AES`
to 
`from Cryptodome.Cipher import AES`

**Comment by skks1212** [comment]
Facing the same issue, did you find a workaround?
